#!/bin/bash

# install the server
npm install
npm run compile

# add the server configuration
get_abs_filename() {
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}
SERVER_EXEC=$(get_abs_filename "server/out/server.js")
mkdir -p ~/.jupyter
cat > ~/.jupyter/jupyter_server_config.json << EOF
{
  "LanguageServerManager": {
    "language_servers": {
      "myst-lsp": {
        "version": 2,
        "argv": ["${server/out/server.js}"],
        "languages": ["ipythongfm"],
        "mime_types": ["text/x-markdown"],
        "display_name": "MyST LSP server"
      }
    }
  }
}
EOF
